### ISSUE TITLE
How to find whether a website is running miner?

### ISSUE THREAD

**Issue by toddkuhreng** [ZeroDot1/CoinBlockerLists#106]
Hi,

This project is a very nice initiative and I would like to contribute to it by adding 
more website URLs that does Javascript based mining. How can I find whether  
a website is mining Crypto currency using visitors CPU power? 

I can crawl through the websites listed by Alexa and grep for "miner" or "coinhive". 
But I realize the Javascript code or these strings could be obfuscated. Is there any 
generic way I could use to find whether a website using by browser to mine? How 
are you guys doing this?

Kind Regards,
Todd

**Comment by ZeroDot1** [comment]
Hi @toddkuhreng I use different ways to find miner.
https://badpackets.net/how-to-find-cryptojacking-malware/ 
I use different search engines, and check different forums to see if there's anything new, sometimes twitter is a big help, because there's a lot of sharing there.
https://www.virustotal.com/de/
https://urlscan.io/
https://github.com/ZeroDot1/CoinBlockerLists/issues/6
I am happy about every contribution.
