### ISSUE TITLE
List of all browser mining domains contains legit mining pool sites that can't be used for covert browser mining

### ISSUE THREAD

**Issue by MoneroOcean** [ZeroDot1/CoinBlockerLists#119]
### Description:

The list that contains all browser mining domains (https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt, https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser) in my humble opinion contains legit mining sites that can not be used for cover browser mining directly like supportxmr.com and moneroocean.stream (they are already listed in "all domains list") so blocking them in this list only affect legit miners on these sites.

For instance:

- supportxmr.com site do not have anything related to web mining at all;
- moneroocean.stream has web mining option but that only works when user willingly presses a button (that is visibly glowing when user decided to press it to start mining) and uses security headers that prevent site to be covertly used as part of other web pages.

So I propose to exclude these mining pool sites from browser mining list and keep them only in "list for administrators to prevent mining in networks".

### Steps To Reproduce:

N/A

### Log Files and Pages Source code:

N/A

### URL and IPlists:

https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser

**Comment by dnmTX** [comment]
And i propose to keep them where they are and if you don't like any of them just whitelist them.Advocating here just making you more complicit in that whole browser mining bullshit.

**Comment by MoneroOcean** [comment]
The thing is that keeping these sites in this list does not help to prevent browser mining at all since browser mining uses websocket connections to other sites like coinhive and these sites in question do not support websocket connections at all.

**Comment by WaLLy3K** [comment]
@ZeroDot1 has two types of lists:

* One for browser mining domains (which has become an issue due to a lack of consent)
* One to prevent any kind of mining (which is a valid issue that administrators may need to tackle)

The primary focus of MoneroOcean is being a mining pool, with (as I understand) an option for a user to opt-into browser based mining. I don't believe it's appropriate for the browser mining blocklist.

For what it's worth, I have no association with @MoneroOcean [prior to this chain of tweets](https://twitter.com/WaLLy3K/status/968423383825199104), and just seek to reduce false positives for Pi-hole users who use lists [posted on my site](https://wally3k.github.io). :slightly_smiling_face:

**Comment by dnmTX** [comment]
How about you open your own repo and make a list for your liking and take all those " legit miners" with you. How is that for PROPOSAL?
P.S. .....and i don't really need a lesson on how things work,not from you at least.....

**Comment by ZeroDot1** [comment]
I have included these hosts in the CoinBolockerLists for browsers to better protect users of the lists. 
There are still a lot of unknowns URLs and many of them put on those pools when the pools are not reachable, in most cases also the mining doesn't work, that's why these hosts are in the list. 

@MoneroOcean If you don't like this, please create your own personal white list.

**Comment by MoneroOcean** [comment]
OK. I appreciate your answer. I do not have plans to create any kind of extra lists. It is not my business)
