### ISSUE TITLE
HostsMan CoinBlockerLists Error!

### ISSUE THREAD

**Issue by ZeroDot1** [ZeroDot1/CoinBlockerLists#129]
@superlex @dnmTX
Is it possible that you test it once, I don't have a Windows computer at the moment to test it myself. 
http://zerodot1.pytalhost.org/dl/ 
It's only a temporary solution.

**Comment by dnmTX** [comment]
@ZeroDot1  i just tested using this URL: http://zerodot1.pytalhost.org/dl/list_browser.txt  which is the one for the browser and **IT DOES NOT WORK**.It says that connection is established but loads emty hosts file for some reason.The link that you posted won't even establish connection.Not sure where the problem is.
![capture](https://user-images.githubusercontent.com/34774426/37557643-9e2a86b8-29d5-11e8-8ff6-e93a80c0c676.PNG)
![capture1](https://user-images.githubusercontent.com/34774426/37557644-a190a15c-29d5-11e8-9b63-3e91b867e7f0.PNG)

**Comment by ZeroDot1** [comment]
@dnmTX 
Yes, that's a good idea, but when sorting it gets mixed up again and again and so it's no longer at the beginning of the document as it should be, and it's too time-consuming to re-insert it every time.

**Comment by superlex** [comment]
Hi ZeroDot1,
sorry I can't help you with HostsMan, I could with wget and curl if you need.

**Comment by dnmTX** [comment]
@superlex no worries man,i got it 👍

**Comment by ZeroDot1** [comment]
The best solution would be to write a script for Windows and Linux with which you can download the files and insert them into the existing Hosts file without getting duplicates.

**Comment by ZeroDot1** [comment]
There is already a solution for Linux: https://github.com/pyamsoft/update-hosts

**Comment by ZeroDot1** [comment]
@dnmTX @superlex I am looking for a good solution for Windows, and when I have finished something I will report.

**Comment by dnmTX** [comment]
Look at the @ScriptTiger's repo.He got something for windows that probably can be modified to fetch from different URL in this case the one i posted earlier.

**Comment by dnmTX** [comment]
@ZeroDot1 whatever the solution is if those entries are not present and one wants to use it individually it would not be possible with HostMan anyway.Just saying.

**Comment by ZeroDot1** [comment]
HostsMan is not a solution, Hostsman is a problem.
I'll write a script for Windows, and then you can test it when it's ready. I can't at the moment because I don't have a computer with Windows to test it myself.

**Comment by ZeroDot1** [comment]
@dnmTX @superlex Here is a simple script,m but it does not work correctly yet because the standard entries in the Hosts file are still not available.

```cmd
:: CoinBlockerLists Downloader
:: This script will first create a backup of the original or current hosts
:: file and save it in a file titled "hosts.bak"
:: It will then download the latest updated hosts file
:: Finally the DNS cache will also be refreshed.
:: THIS BAT FILE MUST BE LAUNCHED WITH ADMINISTRATOR PRIVILEGES

TITLE CoinBlockerListsDownloader

cd \
mkdir tmp

:: Check if we are administrator. If not, exit immediately.

>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
if %ERRORLEVEL% NEQ 0 (
    ECHO This script must be run with administrator privileges!
    ECHO Please launch command prompt as administrator. Exiting...
    EXIT /B 1
)
if not exist "%WINDIR%\System32\drivers\etc\hosts.bak" (
	COPY %WINDIR%\System32\drivers\etc\hosts %WINDIR%\System32\drivers\etc\hosts.bak
    )
if not exist "%WINDIR%\System32\drivers\etc\hosts.original" (
	COPY %WINDIR%\System32\drivers\etc\hosts %WINDIR%\System32\drivers\etc\hosts.original
    )
:: Download Latest Updated Hosts File
:: Uses a Windows component called BITS
:: It has been included in Windows since XP and 2000 SP3

bitsadmin.exe /transfer "Download Fresh Hosts File" https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts C:\tmp\hosts

echo Move new hosts file in-place

:: Move new hosts file in-place

COPY C:\tmp\hosts %WINDIR%\System32\drivers\etc\

echo Flush the DNS cache

:: Flush the DNS cache

ipconfig /flushdns

echo ALL DONE! Your computer is now protected against cryptojaking.

```

**Comment by ZeroDot1** [comment]
@superlex  Do you have an idea how to insert the missing lines at the beginning of the Hosts file?

I think the best solution is to write the missing entries via this script into the Hosts file, but I don't know how to solve this best so that it works.

**Comment by ZeroDot1** [comment]
@dnmTX @superlex I uploaded the script here, but I can't confirm if it works as I thought.
https://github.com/ZeroDot1/CoinBlockerLists/blob/master/tools/CBListsDownloader.bat

**Comment by dnmTX** [comment]
I'll test it later and let you know if any problems.

**Comment by funilrys** [comment]
Hello there,
Here is what is in the [hosts.windows.template](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/templates/hosts.windows.template) we use under [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist):

```
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
```

It's minimal but seems to work correctly.

**Comment by ZeroDot1** [comment]
@dnmTX Thank you very much.

**Comment by funilrys** [comment]
Also Ultimate is different but it should be (at least):

```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost ip6-localhost ip6-loopback
fe80::1%lo0 localhost
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
0.0.0.0 0.0.0.0
```

**Comment by funilrys** [comment]
We did differently for windows as there were some issues with some of the domains which should be used ... (Windows is so strange sometimes ...)

**Comment by ZeroDot1** [comment]
@funilrys The only problem I have is to put the default entries with the script in the Hosts file at the beginning of the file.

**Comment by funilrys** [comment]
May I ask which script are you using?

**Comment by ZeroDot1** [comment]
@funilrys  https://github.com/ZeroDot1/CoinBlockerLists/blob/master/tools/CBListsDownloader.bat

**Comment by funilrys** [comment]
Me either so I can't be helpful ...

**Comment by ZeroDot1** [comment]
@funilrys  I think at some point I have the missing parts for the Windows computer together, then I can test it.

**Comment by superlex** [comment]
@ZeroDot1 ,
you could start from default Windows hosts file, something like this:
`type C:\tmp\hosts >> %WINDIR%\System32\drivers\etc\hosts`
instead of
`COPY C:\tmp\hosts %WINDIR%\System32\drivers\etc\`

_type_ should be equivalent to unix _cat_

**Comment by ScriptTiger** [comment]
Just for clarification, you are trying to automatically update a hosts file from a given URL and insert the following lines at the top of it but not include duplicates?
```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost ip6-localhost ip6-loopback
fe80::1%lo0 localhost
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
0.0.0.0 0.0.0.0
```

As @dnmTX mentioned, my script does include a mechanism to update the hosts file in place and you can insert custom entries before or after or in between however you want. Right now my script is obviously tailored to work specifically with the hosts files from Steven Black, but I could easily make a new one to work with any hosts file URL.

Basically you use a for loop to read the contents of the current hosts file to a temporary file, as you shouldn't write to a file that is being read from at the same time. You can then make conditional statements within the for loop to trigger inserting further information from wget, files, etc., wherever you want in the file based on the contents of the lines or whether it's at the beginning or end of a file, etc. When reading from the sources, you can use findstr /v "localhost$ local$ loopback$ localdomain$ broadcasthost$ allnodes$ allrouters$ ^0.0.0.0.0.0.0.0$" to read from the sources while ignoring duplicate entries. You then replace the hosts file with the temporary file and process complete.

For performance reasons, you should also group the write operations together in groups larger than just writing each line, like this "echo %line%>>file". This will be extremely slow as the computer is stopping each line to perform a write operation. In my script the entire operation is a single write, which means everything is done in RAM and then dumped all together at once at the end. You can see an example of this on my script here:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/master/Hosts_Update.cmd
Where there is only a single write to "%TEMP%hosts".

**Comment by ScriptTiger** [comment]
I've started a new Hosts-AutoUpdate repo offline to handle general hosts files. The specs will be as follows:

Hosts_Update.cmd: script
VERSION: version of script
custom.txt: list of custom entries to insert (duplicates ignored) (blacklist)
ignore.txt: list of strings to ignore (whitelist)
sources.txt: list of URLs to download to data directory
data/URL.txt: files to iterate and pull from (duplicates ignored)
%TEMP%/URL.txt: temporary directory of source files to hash against current files to check if up to date or not or if an update is needed or not

hosts file entries managed by script will be within designated area of hosts file (#### BEGIN MANAGED HOSTS #### and #### END MANAGED HOSTS ####)

Any other feature requests?

**Comment by dnmTX** [comment]
Ahhh.....YES.....couple more suggestions if you don't mind(of course).Great idea for the "compressed" format,would request option to specify how many entries per line(right now i'm with 5 entries and it's flying).
Option to remove comments and empty lines(too many of those in the @StevenBlack's list) but without removing the whitelisted entries.
Option to when update to replace the hosts file with the new one instead of just adding new entries also to check for duplicates.
All the above that i mentioned HostMan can do which makes the whole process very easy if you can mange this i'll personally move to your script.
@ZeroDot1  i would highly encourage you to get on board with this,sometime you are little stubborn when it comes to scripting and stuff but as you see everyone here is trying to help,it's called community.
KUDOS to @ScriptTiger  for the effort and willingness to help.
@ScriptTiger  will post screenshot of my hosts file just to have an idea what i mean.
![capture](https://user-images.githubusercontent.com/34774426/37639812-e31f5692-2be0-11e8-9a48-32bef588cba8.PNG)

**Comment by ScriptTiger** [comment]
I've updated my original post above with your additional specs. For the most part my current scripts I use to build my alternate blacklist formats (https://scripttiger.github.io/alts/) already allow for the additional options you've requested, such as removing excess white space, comments, etc. I'm not sure if there would be any reason to give an option of how many domains per line. For now my current script compresses to the maximum of 9. I would think people would either want it compressed or not, and I'm not sure if there would be much interest in a moderately compressed format, but I'd love to hear your case on that.

Also, the compressed format I offer at the above link also includes all comments, but compresses contiguous comment blocks to a single line. This is to be in keeping with the licensing since those files are pre-generated and distributed via the web, so I am obligated to distribute them with comments. However, personally I also like comments even when generating blacklists for personal use just because it makes reviewing them easier if you have the thoughts of the curators there with the entries. But I know many people don't really care about that and weeding out the comments entirely is even simpler than the process I have already made to include them. In the end everything will be an option, but I'm just mentioning this in case others might be interested in seeing a format with comments, but without excessive comment lines.

**Comment by dnmTX** [comment]
I've tried with 9 in the past,also with 3.In both cases browsing speed didn't change so i settled with 5 and at least for me is faster but this is on individual bases.That's why i ask for a option to choose cause if for me 5 lines is faster for somebody else it might be slower or no change.We talking about Windows here,there is no such a thing "ONE WORKS FOR ALL"
I understand your point of view when it comes to licensing and notes etc. but look at my point of view as a user.Basically(for example when i use HostMan) i'm downloading @StevenBlack's file which has all those comments,spaces,it's up to every license requirement and then when it comes to me i can compress it remove whatever i want and make it as small as possible for the best performance and i don't think that StevenBlack cares about it cause i'm not modifying his file but the one i downloaded which is mine.I think you got my point,right? We need those options present to get the best possible performance out of those large files,especially on Windows based systems.And i'm really not sure that anyone or at least the majority care about having any comments.It's easy to troubleshoot now days even for not really tech savvy once.It's basically design to keep you safe not to read from it.

**Comment by ScriptTiger** [comment]
No worries, everyone loves options. I'll knock them out one by one and see what you guys think. I've edited my above post again and added a couple more to the list. Once I get some time to work on it a bit more, I'll initialize the public repo with this checklist in the README as the project mission/vision.

**Comment by ScriptTiger** [comment]
Is there a reason why it would matter if custom entries are inserted at the beginning or ending of a file? It seems a lot of the comments above talk about having the localhost, loopback, and IPV6 stuff all together at the top, but I am not sure if it matters as long as they are all in the file. My current scripts add them last, but they could easily be inserted before or even two different custom lists for before and after. Are there any opinions on this as to why it matters? In the case of a single custom list added to the end, if the entries are already present than the duplicates are not added twice and it's just basically making sure they are added no matter what but their position in the file shouldn't matter.

**Comment by ScriptTiger** [comment]
@ZeroDot1, there were so many comments on this issue I totally neglected to address your root issue, so my apologies. HostsMan's internal HTTP(S) fetcher isn't compatible with the way github.com serves documents because it's not strictly an HTTP(S) web server and has integrations with multiple other protocols with dynamic forwarders, redirectors, and virtual directories that confuse some fetchers. The way I handle this is I serve downloadable content from my github.io domain, which is strictly an HTTP(S) web server and compatible with HostMan. Not only HostMan has this problem and it's best practice to serve documents that are intended to be downloaded from either your github.io domain (ZeroDot1.github.io) or a mirror site. Using the github.io domain that is associated with your account is probably easiest since you are already using git and already have clones of your repos locally, so scripting content to be synced between git repos is probably going to be much easier and simpler than scripting a sync with a mirror elsewhere. This should be the easiest solution for your current problem.

Also, for those interested, I am still working on a general hosts manager script, but I am reviewing and updating all of my current blacklist scripts first so I can use the best methods on the general script which basically has the potential to replace all of them.

**Comment by ZeroDot1** [comment]
@ScriptTiger I have removed the `http://zerodot1.pytalhost.org/dl/` mirror a test showed me that the links you inserted for me work everywhere. Thank you for your work.  

The HostsMan problem is solved. 

However, I think it is good if there is a simple script with which you can install and update the hosts files under Windows without any additional software like wget.
Using additional software like wget is not possible in many administrative environments for security reasons.
so I would suggest doing everything with Windows' proprietary tools.

**Comment by ScriptTiger** [comment]
I have actually dropped wget from all of my projects, so there is now only a single script using only the standard built-in Windows utilities and several configuration files, like the ignore list, custom list, etc. I will also implement an INI file in the new manager since it will have quite a bit more settings and there's no need for users to go through a full setup every time. Feel free to check out the latest AutoUpdate here:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/master/Hosts_Update.cmd

As far as the menu goes, the current step by step prompts make it as foolproof as possible, but I have had plans for a better UI for a while and will implement one as soon as I feel the core feature set is stable. I really appreciate the interest and feedback though and am really looking forward to getting the new manager off the ground and seeing where that goes.

**Comment by ZeroDot1** [comment]
@ScriptTiger In the next days I will download Windows and test it in a VM.
Your script looks very good.
