### ISSUE TITLE
gus.host is not a coin mining website

### ISSUE THREAD

**Issue by devsnek** [ZeroDot1/CoinBlockerLists#132]
Hi,

My personal domain (gus.host) has found its way onto a number of hostname block lists. none of the domains (gus.host/www.gus.host/google.gus.host/s.gus.host) actually have any coin miners so please remove them.

thanks,
-gus

**Comment by dnmTX** [comment]
......and the rest of the domains(websites) on **THAT** list are MINE and MINE ONLY!!!!! And i can guarantee,swear,sign whatever you want me to sign that there is not a single MINER in them so...@ZeroDot1 destroy your fraudulent list and JOIN ME in my quest advocating for destroying the remaining useless lists!!!!!!
@devsnek  do you approve my statement bud????????

**Comment by ZeroDot1** [comment]
@devsnek I didn't know I walked around with tomatoes on my eyes. Sorry, I can't remove your site because I found miner and or other malware.
I recommend that you check your site for malware and remove it.
If you are not able to do this yourself, contact experts who can.
Pages like Virus Total show me warnings when I scan your page.
As long as this is the case, the page will stay on the list. 
Example:
`https://gus.host/coins.js`
https://www.virustotal.com/de/file/c80eced3277166f0f0cfa4da15152a79cfcc549598aeb5b2f375b1d4aa6a80c4/analysis/
https://www.virustotal.com/de/url/14325f1697d96cb7868e62651414b7a9e7e62e0a2c183e4329e34c0e4def0988/analysis/

**Comment by devsnek** [comment]
@zerodot1 if you could spare 15 seconds of your precious time you could go to my site and see it's a static html page with a link to my github and twitter. it contains no JavaScript except for a console.log. I can say with 100% certainty that my site contains no malware, it's a github pages bucket. feel free to check out my github and see that I'm not exactly a random not trustworthy person. there is no "coins.js" on any domains I own. if someone comes here and complains it should be your due diligence to verify the claim, not theirs. otherwise you clearly shouldn't be maintaining a list.

**Comment by ZeroDot1** [comment]
@devsnek I'm going to look into it.

**Comment by ZeroDot1** [comment]
@devsnek I apologize for the inconvenience, I have checked everything, the site is clean, so I will remove it from the list, should there be back miner on the site it will be added again.
With the next update this will be done.

**Comment by ZeroDot1** [comment]
URLS REMOVE:
```cmd
gus.host
www.gus.host
google.gus.host
s.gus.host
```

**Comment by ZeroDot1** [comment]
@devsnek 
Your site is now on the white list, about a small donation to support the CoinBlockerLists I would be very happy.
https://www.amazon.de/hz/wishlist/ls/2DDEDPJU2996I?filter=unpurchased&language=en_GB&sort=price-asc&type=wishlist 

I apologize again for the inconvenience.
Take a look at the changes here:
https://github.com/ZeroDot1/CoinBlockerLists/commit/9c150d70703f8f36d6b6f805f5f2e8947407fda9

@devsnek 
If you have any other problems do not hesitate to contact me, because this is the only way to solve the problem quickly.

**Comment by devsnek** [comment]
@ZeroDot1 thank you 👍
