### ISSUE TITLE
Creating a new homepage

### ISSUE THREAD

**Issue by ZeroDot1** [ZeroDot1/CoinBlockerLists#136]
The page generated automatically by Github is not good enough, you can't place enough information there. Therefore a new homepage will be created.
All of them are written completely by hand.

**Comment by ZeroDot1** [comment]
https://zerodot1.github.io/CoinBlockerListsWeb/

**Comment by ZeroDot1** [comment]
Most of it is finished.
https://zerodot1.github.io/CoinBlockerListsWeb/downloads.html
https://zerodot1.github.io/CoinBlockerListsWeb/aboutthisproject.html

**Comment by dnmTX** [comment]
Mine too...(15" Laptop) 😄

**Comment by ZeroDot1** [comment]
@dnmTX Can you check again to see if it's better now, I changed it.
https://zerodot1.github.io/CoinBlockerListsWeb/aboutthisproject.html

**Comment by dnmTX** [comment]
@ZeroDot1  still the same here,i can post screenshot if you want so you can see.

**Comment by ZeroDot1** [comment]
@dnmTX Can you take a sceenshot, that would very helpful for me to solve the problem.

**Comment by dnmTX** [comment]
@ZeroDot1  here you go.....
![coinblockerlists](https://user-images.githubusercontent.com/34774426/39261312-b2bbcafe-4881-11e8-88f0-8998465a62c4.png)

**Comment by ZeroDot1** [comment]
@dnmTX OK, it looks perfect, the table automatically adjusts the width to the contents of the table when you set the width, e.g. 800px the width of the table is not automatically adjusted anymore, so I changed the table to auto so that the table adapts to your screen width and not to the container.

**Comment by ZeroDot1** [comment]
@dnmTX Yes, I work mostly with Linux, because it is safer, and also the screen magnifier I need works very good. 
This is what it looks like on my computer screen.
Sorry, the picture is not so good, the monitor is very old, and I have repaired it several times.
![bildschirmfoto_2018-04-26_04-46-31](https://user-images.githubusercontent.com/28985171/39283096-d818e0a8-490c-11e8-82e4-05ef3820fd81.png)

**Comment by dnmTX** [comment]
@ZeroDot1  on mine still looks the same as the screenshot i send you,no big deal for me,i can scroll down if i need to,i just want it you to know how it looks......Now....about the Linux,i just need your expertise due to i just made my first steps into it....up front apologize for the long post......
This is the deal....i want it to use something better then the Windows DNS crappy service so i loaded custom firmware on my router(Linux-BusyBox) which had "dnsmasq" preinstalled already,this way i can protect my phone as well if have to browse from it.Took me a while to set it up the way i like so i wrote a short script to download the desire hosts files,organize them bla bla bla and pass it to dnsmasq to use it.Now,note this,router's OS does all that so i've tried to make it as efficient as possible,i'm just passing the command remotely(SSH) to the router to activate the script.Right now for the whole process to complete it takes about 10 sec. and the router's CPU is at 100% while doing it.Can you look at the script and give me you expert opinion and also advise if something can be changed in order to make it faster and more efficient as well.Thank you.Here you go:

#!/bin/sh

wget https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts -O /media/AiDisk_a1/Hosts/addhosts
wget https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt -O /media/AiDisk_a1/Hosts/windowshosts
sed -i '/#/d; /^$/d; /^255/d; /^127/d; /::/d; /^0.0.0.0 0.0./d' /media/AiDisk_a1/Hosts/addhosts
sed -i '/^#/d; /^$/d' /media/AiDisk_a1/Hosts/windowshosts
# remove duplicates and merge both files
awk '!x[$0]++' /media/AiDisk_a1/Hosts/addhosts /media/AiDisk_a1/Hosts/windowshosts > /media/AiDisk_a1/Hosts/hosts
# Just in case check again for duplicates in the new "hosts" file
uniq -d /media/AiDisk_a1/Hosts/hosts
# prints the number of lines to compare(for testing)
wc -l /media/AiDisk_a1/Hosts/hosts 
# removes the original files
rm /media/AiDisk_a1/Hosts/addhosts /media/AiDisk_a1/Hosts/windowshosts
# restarts dnsmasq
killall dnsmasq && /usr/sbin/dnsmasq

P.S. Took me 10 sleepless days to research it and make it work so i'm kind of proud of it  😃 
the "awk" command is the most demanding one(9 sec.) but everywhere is recommended for such a task as the fastest one to do it comparing to "sed" or "cat" etc.

**Comment by dnmTX** [comment]
#test

**Comment by ZeroDot1** [comment]
@dnmTX The script is OK so I would only make small changes to make it more fail-safe.
```bash
#!/usr/bin/env bash
echo "Update hosts, this can take some time please wait until the process is finished."
wget --referer=https://github.com/ -t 20 --no-check-certificate https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts -O /media/AiDisk_a1/Hosts/addhosts
wget --referer=https://github.com/ -t 20 --no-check-certificate https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt -O /media/AiDisk_a1/Hosts/windowshosts
sed -i '/#/d; /^$/d; /^255/d; /^127/d; /::/d; /^0.0.0.0 0.0./d' /media/AiDisk_a1/Hosts/addhosts
sed -i '/^#/d; /^$/d' /media/AiDisk_a1/Hosts/windowshosts
# remove duplicates and merge both files
awk '!x[$0]++' /media/AiDisk_a1/Hosts/addhosts /media/AiDisk_a1/Hosts/windowshosts > /media/AiDisk_a1/Hosts/hosts
# Just in case check again for duplicates in the new "hosts" file
uniq -d /media/AiDisk_a1/Hosts/hosts
# prints the number of lines to compare(for testing)
wc -l /media/AiDisk_a1/Hosts/hosts
# removes the original files
rm /media/AiDisk_a1/Hosts/addhosts /media/AiDisk_a1/Hosts/windowshosts
# restarts dnsmasq
killall dnsmasq && /usr/sbin/dnsmasq
echo "Done!"
exit 0
```
‘--no-check-certificate’
Don’t check the server certificate against the available certificate authorities. Also don’t require the URL host name to match the common name presented by the certificate.

As of Wget 1.10, the default is to verify the server’s certificate against the recognized certificate authorities, breaking the SSL handshake and aborting the download if the verification fails. Although this provides more secure downloads, it does break interoperability with some sites that worked with previous Wget versions, particularly those using self-signed, expired, or otherwise invalid certificates. This option forces an “insecure” mode of operation that turns the certificate verification errors into warnings and allows you to proceed.

If you encounter “certificate verification” errors or ones saying that “common name doesn’t match requested host name”, you can use this option to bypass the verification and proceed with the download. Only use this option if you are otherwise convinced of the site’s authenticity, or if you really don’t care about the validity of its certificate. It is almost always a bad idea not to check the certificates when transmitting confidential or important data. For self-signed/internal certificates, you should download the certificate and verify against that instead of forcing this insecure mode. If you are really sure of not desiring any certificate verification, you can specify –check-certificate=quiet to tell wget to not print any warning about invalid certificates, albeit in most cases this is the wrong thing to do.

Another tip, set up the Cloudflare DNS server, so you are safer and faster on the Internet. 
All required information is available at the following website: https://1.1.1.1/ 
The next step is to update the router's operating system and keep it up to date whenever possible.
I can't say why it's 100% loaded, because I don't know exactly which device and which software it is, but if it's only short it shouldn't be a problem.

**Comment by dnmTX** [comment]
@ZeroDot1  thanks for taking the time to examining it and the suggestions,i feel better now when there is a approval from more experienced in that field.Let me give you my thoughts also:
1. Not sure that the "fail-safe" is really necessary here due to the links i'm using are from reputable github.com sources but i'll probably include the "--referer" part just in case.About the "--no-check-certificate" i'll include it in the future if it's start showing connection errors i guess.
2. Cloudflare DNS is already set as to be the first thing when the signal comes from the modem,even before the dnsmasq(got that thing covered) Here is a sample from the log:

dnsmasq[507]: read /etc/hosts - 3 addresses
dnsmasq[507]: read /media/AiDisk_a1/Hosts/hosts - 55774 addresses
dnsmasq-dhcp[507]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
dnsmasq[507]: using nameserver 1.1.1.1#53
dnsmasq[507]: using nameserver 1.0.0.1#53

3.The Firmware is denerally old due to router is a old model and the person who designed it i guess gave up on it but there are few enthusiast that took over to keep it up to date,especially when it comes to security.
4. About the "100% CPU"...well it's a router,not a full blown PC so it's weak,you know,it's not design to do such a tasks(this is from the log: "CPU/OCP/SYS frequency: 500/166/166 MHz") but considering all that i'm still happy with the results and yes it goes to 100% for a short time,probably when it does the "awk" command.
5. The "exit 0" is a good idea,i just read about it and will definitely include.Important part that i missed.

Thank you again @ZeroDot1 ,appreciate all the input. 😄

**Comment by ZeroDot1** [comment]
@dnmTX No problem, here's an better exit code.
This should work much better than using only `exit 0`.

```bash
exit_job(){
echo "$1"
exit 0
}
```

**Comment by ZeroDot1** [comment]
The homepage now also has Twitter Cards.
![bildschirmfoto_2018-04-26_23-09-58](https://user-images.githubusercontent.com/28985171/39334981-5e92d004-49b1-11e8-90b5-3f8865e3f306.png)

**Comment by ZeroDot1** [comment]
@dnmTX https://www.youtube.com/watch?v=hDQrSxud83k take a look at the video.

**Comment by ZeroDot1** [comment]
@Thank you, yes, you're right, I'll remove some things from the list.

**Comment by dnmTX** [comment]
@ZeroDot1 the sooner the better.I already posted it, encouraging for donations #592. Also the list is so long that when you open the page is loading like 5 min.Just FYI.

**Comment by dnmTX** [comment]
So many DVD's there.Can't you just download those movies from the net somewhere???...it's 2018 for heaven's sake. 😄

**Comment by ZeroDot1** [comment]
My internet connection is very slow, Netflix and other services don't work, and would be too expensive for me.
But I just deleted more DVDs from the list, there are only a handful left on the list.

**Comment by dnmTX** [comment]
Ahh...ok....sorry,didn't mean to be a-hole about it.No excuse for my stupid questions though.Will refrain from expressing opinion in the future about things that i don't know nothing about.(deleting my previous post out of respect....sorry again)

**Comment by ZeroDot1** [comment]
No problem, it's impossible to know everything.

**Comment by ZeroDot1** [comment]
@dnmTX I added a donation popup to the download page, what's your opinion, is that a good idea or not?
Or do I have to change something to make it better?
https://zerodot1.github.io/CoinBlockerListsWeb/downloads.html

**Comment by dnmTX** [comment]
@ZeroDot1  i think it's too aggressive (it's like you telling everyone that they have to donate).I've seen in some web pages popup is sliding up from the bottom of the page for certain seconds and then sliding down(it would be more appropriate),not sure that you can make it work though.Or simply make something on the left side like....here example just to give you an idea:
![coinblockerlists](https://user-images.githubusercontent.com/34774426/39402472-e0256f3a-4b25-11e8-9060-c7817ef70dd6.png)

**Comment by ZeroDot1** [comment]
@dnmTX Your example is very good, I will change that right now, you are right it is too aggressive.
Sorry to answer so late, I was looking for a used monitor the whole day. My monitor is flickering again, unfortunately I haven't found anything suitable that I can buy, on Ebay a lot of crap is offered.

**Comment by ZeroDot1** [comment]
Done! : 
![screenshot-2018-4-29 coinblockerlists - downloads - simple lists that can help to prevent illegal mining in the browser or](https://user-images.githubusercontent.com/28985171/39410407-feacddc6-4bf7-11e8-82d4-69646002d5d5.png)

**Comment by dnmTX** [comment]
@ZeroDot1  the list looks much better(if there is a way to sort the tech/computer related items to be on the top will be even better), and yeah,at one point i was thinking to tell you to look for better deals giving the fact that it's Amazon and there is always deals there cause some(non brand) items were  kind of expensive and even for making donation still didn't worth to spend so much on them.Sorry to hear about your monitor troubles,fingers crossed to find something good(...and cheap) soon.Web page looks better too,glad you took my advise.Couple more thoughts about the donation list:
I like the items that has explanation what would they be purposed to(more of that would help).Generally speaking when one decide to make donation is expecting to give some amount of money not to buy stuff,so this is kind of new(at least it was for me) and not every one is familiar with it and explaining what's the item is for kind of help.I'll see if i can do another donation soon and hopefully others will do too.Take care my friend.

**Comment by ZeroDot1** [comment]
I will add some additional comments to the different things on the list to make it a bit better.
I am nearly done with the homepage, only some links on the start page are missing, then the page is finished.

You don't have to donate again, you have already helped me a lot, Since I have the cooler for the computer I can work much better, because the computer doesn't make as much noise as before, I don't know how to thank you for that, that was really great from you to buy me the cooler, Many thanks :)

**Comment by ZeroDot1** [comment]
@dnmTX The homepage is ready, I close the issue.
If you find a bug or have a suggestion for improvement, don't hesitate to write me so I can fix possible bugs as soon as possible.

**Comment by ZeroDot1** [comment]
@dnmTX I cannot release updates for the CoinBlockerLists at the moment, My computer had a hard disk crash.
